# Generated by Django 4.0.1 on 2022-01-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Previous price'),
        ),
    ]
